CREATE OR ALTER PROCEDURE SENDMESSAGETOALL 
	@MESSAGE VARCHAR(255) = NULL
AS
  BEGIN
      SET NOCOUNT ON;

      DECLARE @ID INT
      DECLARE MEMBER_CURSOR CURSOR FOR
        SELECT MEMBER_ID
        FROM   DBO.MEMBER

      OPEN MEMBER_CURSOR
      FETCH NEXT FROM MEMBER_CURSOR INTO @ID
  
      WHILE @@FETCH_STATUS = 0
        BEGIN
            INSERT INTO DBO.MESSAGE
                        (MEMBER_ID,TEXT,IS_SEEN)
            VALUES      (@ID,@MESSAGE,0);

            FETCH NEXT FROM MEMBER_CURSOR INTO @ID
        END

      CLOSE MEMBER_CURSOR
      DEALLOCATE MEMBER_CURSOR
  END
GO
EXEC SENDMESSAGETOALL 'AICup is coming soon'


CREATE OR ALTER PROCEDURE CREATEEVENT 
	@EMAIL NVARCHAR(50) = NULL,
	@PASSWORD VARCHAR(50) = NULL,
	@PHONE_NUMBER VARCHAR(50) = NULL,
	@THUMBNAIL VARCHAR(50) = NULL,
	@CATEGORY_TITLE VARCHAR(50) = NULL,
	@ORGANIZER_NAME VARCHAR(50) = NULL,
	@NAME VARCHAR(50) = NULL,
	@PRICE DECIMAL(12, 3) = NULL,
	@PLACE VARCHAR(50) = NULL,
	@TYPE VARCHAR(15) = NULL,
	@DESCRIPTION VARCHAR(500) = NULL,
	@EXP_REGISTRATION DATETIME = NULL
AS
  BEGIN
      SET NOCOUNT ON;

      DECLARE @ORGANIZER INT
      DECLARE @CATEGORY VARCHAR(50)
      DECLARE @EVENT_ID INT

      SELECT @ORGANIZER = ORGANIZER_ID
      FROM   DBO.ORGANIZER
      WHERE  NAME = @ORGANIZER_NAME

      IF @ORGANIZER IS NULL
        BEGIN
            RAISERROR('Organizer not found',16,1)
            RETURN
        END

      SELECT @CATEGORY = TITLE
      FROM   DBO.CATEGORY
      WHERE  TITLE = @CATEGORY_TITLE

      IF @CATEGORY IS NULL
        BEGIN
            RAISERROR('Category not found',16,1)
            RETURN
        END

      INSERT INTO DBO.MEMBER
                  (EMAIL,PASSWORD,PHONE_NUMBER,THUMBNAIL)
      VALUES      (@EMAIL,@PASSWORD,@PHONE_NUMBER,@THUMBNAIL)

      SELECT @EVENT_ID = MEMBER_ID
      FROM   DBO.MEMBER
      WHERE  EMAIL = @EMAIL
             AND PASSWORD = @PASSWORD

      INSERT INTO DBO.EVENT
                  (EVENT_ID,CATEGORY,ORGANIZER_ID,NAME,PRICE,PLACE,TYPE,
                   DESCRIPTION,
                   EXP_REGISTRATION)
      VALUES      (@EVENT_ID,@CATEGORY,@ORGANIZER,@NAME,@PRICE,@PLACE,@TYPE,
                   @DESCRIPTION,
                   @EXP_REGISTRATION )
  END
GO
EXEC CREATEEVENT
  'robo@iut.ac.ir',
  'cd8vs6g743d',
  NULL,
  NULL,
  'Educational',
  'Isfahan university of technology',
  'RoboIUT',
  100000,
  'Isfahan university of technology',
  'Both',
  'An Robotic competition',
  '2023-12-12 00:00:00'


CREATE OR ALTER PROCEDURE CREATEDISCOUNT 
	@PERCENT INT,
	@EVENT_NAME NVARCHAR(50),
	@EXPIRE_DATE DATETIME
AS
  BEGIN
      SET NOCOUNT ON;

      DECLARE @EVENT INT = (SELECT EVENT_ID
         FROM   DBO.EVENT
         WHERE  NAME = @EVENT_NAME)

      IF @EVENT IS NULL
        BEGIN
            RAISERROR('Event not found!',16,1)
            RETURN
        END

      DECLARE @DISCOUNT DECIMAL(2, 0) = ( 100 - @PERCENT ) / 100

      IF Getdate() > @EXPIRE_DATE
        BEGIN
            RAISERROR('expiraion date not valid!',16,1)
            RETURN
        END

      --generate random code
      DECLARE @RANDOM_CODE VARCHAR(8)
      SELECT @RANDOM_CODE = COALESCE(@RANDOM_CODE, '') + Char( CASE WHEN R
                            BETWEEN
                            0 AND 9
                                   THEN 48 WHEN R
                                   BETWEEN 10 AND 35 THEN 55 ELSE 61 END + R)
      FROM   MASTER..SPT_VALUES
             CROSS JOIN (SELECT Cast(Rand(Abs(Checksum(Newid()))) * 61 AS INT) r) A
      WHERE  TYPE = 'P'
             AND NUMBER < 8

      INSERT INTO DBO.DISCOUNT
                  (CODE,EVENT_ID,DBO.DISCOUNT."PERCENT",EXP_DATE)
      VALUES      (@RANDOM_CODE,@EVENT,@PERCENT,@EXPIRE_DATE)
  END
GO
EXEC CREATEDISCOUNT
  @EVENT_NAME = N'AICup',
  @PERCENT = 20,
  @EXPIRE_DATE = '2025-05-10 23:59:59' 